name: Deploy-Staging-Production

on:
  push:
    branches:
      - main
      - develop

  workflow_dispatch:

jobs:
  deploy_staging:
    runs-on: ubuntu-latest
    environment:
      name: staging
      url: https://yahoo.co.jp
    if: github.ref == 'refs/heads/develop'
    steps:
      - run: echo deploy staging
      - run: echo vars ${{ vars.SAMPLE_VAR }}

  deploy_production:
    runs-on: ubuntu-latest
    environment:
      name: production
      url: https://google.com
    if: github.ref == 'refs/heads/main'
    steps:
      - run: echo deploy production
      - run: echo vars ${{ vars.SAMPLE_VAR }}
